version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./ToDoList:/app

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - ./ToDoList:/models